export const SHOW_ERROR = 'SHOW_ERROR';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const TASK_CREATE_START = 'TASK_CREATE_START';
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL';

export const TASK_READ_START = 'TASK_READ_START';
export const TASK_READ_SUCCESS = 'TASK_READ_SUCCESS';
export const TASK_READ_FAIL = 'TASK_READ_FAIL';

export const TASKS_READ_START = 'TASKS_READ_START';
export const TASKS_READ_SUCCESS = 'TASKS_READ_SUCCESS';
export const TASKS_READ_FAIL = 'TASKS_READ_FAIL';

export const TASK_UPDATE_START = 'TASK_UPDATE_START';
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS';
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL';

export const TASK_DELETE_START = 'TASK_DELETE_START';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL';

export const TASK_CLEAR = 'TASK_CLEAR';
export const TASKS_CLEAR = 'TASKS_CLEAR';

export const USER_UPDATE_START = 'USER_UPDATE_START';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
